name         'torrancew-accounts'
version      '0.0.5'
source       'https://github.com/pcfens/puppet-account'
author       'torrancew'
license      'Apache License, Version 2.0'
summary      'A module to manage most typical aspects of UNIX user accounts'
description  'A module to manage User accounts (as well as groups, home dirs and SSH keys)'
project_page 'https://github.com/pcfens/puppet-account'
